# Generated by Django 6.1.1 on 2026-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fraud_probability', models.FloatField()),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Async Verification'), ('MANUAL_REVIEW', 'Routed to Manual Review'), ('REJECTED', 'Rejected (High Fraud Risk)')], max_length=32)),
                ('mode', models.CharField(choices=[('REAL_TIME', 'Real-Time Streaming Feature Serving'), ('DEGRADED_STALE', 'Degraded Mode (Staleness > 60s)'), ('COLD_START', 'Cold Start (No Prior Redis Features)'), ('INFRA_DEGRADED', 'Degraded Mode (Infrastructure Outage)')], max_length=32)),
                ('staleness_seconds', models.FloatField(blank=True, null=True)),
                ('features_snapshot', models.JSONField(default=dict)),
                ('model_version', models.CharField(default='v1.0.0', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'scored_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='scored_tran_user_id_2177ab_idx'), models.Index(fields=['decision', '-created_at'], name='scored_tran_decisio_2428b7_idx')],
            },
        ),
    ]
